### ISSUE TITLE
[BUG] Netflix tidak bisa dibuka, sudah pakai GoodbyeDPI juga

### ISSUE THREAD

**Issue by dickys11** [gvoze32/bebasid#774]

**Comment by tova04** [comment]
Sama kejadiannya. Tadi pagi masih bisa, pas dicoba sekitar sejam lalu tidak bisa lagi.

**Comment by blueais** [comment]
sama, barusan mo nonton, This site can’t be reached

**Comment by juskangkung** [comment]
coba ip address di hostnya diganti 54.71.111.34 yg punyanya netflix.com

**Comment by blueais** [comment]
update 171019-07.10
sy coba tambahkan ip netflix di host, sementara berhasil sih >>
34.213.151.116 netflix.com www.netflix.com
35.160.7.30 netflix.com www.netflix.com
35.160.112.124 netflix.com www.netflix.com
35.164.65.152 netflix.com www.netflix.com
52.26.111.43 netflix.com www.netflix.com
52.37.69.124 netflix.com www.netflix.com
52.37.77.112 netflix.com www.netflix.com
52.37.219.6 netflix.com www.netflix.com
34.246.63.0 netflix.com www.netflix.com
34.249.125.167 netflix.com www.netflix.com
52.49.120.6 netflix.com www.netflix.com
52.209.224.161 netflix.com www.netflix.com
54.76.60.39 netflix.com www.netflix.com
54.77.162.193 netflix.com www.netflix.com
54.171.21.76 netflix.com www.netflix.com
54.229.68.77 netflix.com www.netflix.com

**Comment by gitsuokeda** [comment]
work. thanks for share hostnya masbro

**Comment by dickys11** [comment]
Mantap, work gan

**Comment by gitsuokeda** [comment]
ijin jawab masbro tova04 bisa langsung ke C:\Windows\System32\drivers\etc trus edit file hosts pake notepad++ atau notepad biasa juga bisa masbro.. nanti tambahin hostnya yang udah dikasih sama masbro blueais. semoga membantu ya masbro.

**Comment by tova04** [comment]
@gitsuokeda nice bro thanks, gw kira ga bs edit host langsung dari system32, harus pake exe nya. Ternyata works. Thank you so much!

**Comment by gvoze32** [comment]
Ticket added:
```
54.71.111.34 netflix.com www.netflix.com
34.213.151.116 netflix.com www.netflix.com
35.160.7.30 netflix.com www.netflix.com
35.160.112.124 netflix.com www.netflix.com
35.164.65.152 netflix.com www.netflix.com
52.26.111.43 netflix.com www.netflix.com
52.37.69.124 netflix.com www.netflix.com
52.37.77.112 netflix.com www.netflix.com
52.37.219.6 netflix.com www.netflix.com
34.246.63.0 netflix.com www.netflix.com
34.249.125.167 netflix.com www.netflix.com
52.49.120.6 netflix.com www.netflix.com
52.209.224.161 netflix.com www.netflix.com
54.76.60.39 netflix.com www.netflix.com
54.77.162.193 netflix.com www.netflix.com
54.171.21.76 netflix.com www.netflix.com
54.229.68.77 netflix.com www.netflix.com
```
