### ISSUE TITLE
[DEL] Olymptrade.com

### ISSUE THREAD

**Issue by ezzadeassasin** [gvoze32/bebasid#778]
Olymptrade mulai sore ini tanggal 17 Oktober 2019 tiba2 gak bisa dibuka..

Keterangannya seperti berikut:

> This site can’t be reached
> idolymptrade.com took too long to respond.
> 
> Try:
> Checking the connection
> Checking the proxy and the firewall
> Running Windows Network Diagnostics
> ERR_CONNECTION_TIMED_OUT
> Check your internet connection.
> Check any cables and reboot any routers, modems, or other network devices you may be using.
> 
> Allow Opera to access the network in your firewall or antivirus settings.
> If it is already listed as a program allowed to access the network, try removing it from the list and adding it again.
> 
> If you use a proxy server…
> Check your proxy settings or contact your network administrator to make sure the proxy server is working. If you don't believe you should be using a proxy server: Go to the Main menu > Settings > Change proxy settings… > LAN Settings and deselect "Use a proxy server for your LAN".

**Comment by gvoze32** [comment]
Kita nggak unblock domain itu, coba cek setingan koneksi kamu
