### ISSUE TITLE
[BUG] reddit.com comment nya ngak ngeload

### ISSUE THREAD

**Issue by ch3510** [gvoze32/bebasid#811]
Reddit feednya bisa tapi komennya ngak ngeload, kalo dibuka pake 1.1.1.1 komennya ngeload

Saya pakai adaway dan file hostsnya pakai 
https://raw.githubusercontent.com/gvoze32/bebasid/master/releases/hosts

**Device**
 - OS: [Android 9.0]
 - Browser [Reddit app]
 - Device [Redmi note 8 pro]

**Comment by Bagus23** [comment]
1. udah pakai host paling baru ?
2. buka situs yang diblokir lainnya seperti netflix atau p*rnhub bisa lancar tidak ?

karna di app reddit saya (ios) dan browser tidak masalah.

**Comment by ch3510** [comment]
> 1. udah pakai host paling baru ?
> 2. buka situs yang diblokir lainnya seperti netflix atau p*rnhub bisa lancar tidak ?
> 
> karna di app reddit saya (ios) dan browser tidak masalah.

Netflix sy ga masalah sih soalnya sy pakai first media bukan Speedy Telkom, kalo pr0n hub sih sy ngak ngecek soalnya sy gak nonton gitu2 an, Dan ini udh host paling baru, sya br ganti hp, di hp lama bisa2 aja. To tadi sy coba buka piratebay diblok brarti masih ada masalah, padahal di adaway tulisanya SDH oke...

**Comment by gvoze32** [comment]
Kalau ver mobile kadang suka rewel gan, kecuali kalau pake metode replace pake module magisk misalnya
