### ISSUE TITLE
[BUG] example.com

### ISSUE THREAD

**Issue by saengoko** [gvoze32/bebasid#812]
**Deskripsi mengenai bug**
tidak bisa play

**Screenshot**
![www](https://user-images.githubusercontent.com/58255250/69729697-c4d4c600-1161-11ea-9ea1-a7b3c94b9ca2.JPG)

**Device**
 - OS: Windows 10
 - Browser opera

**Comment by gvoze32** [comment]
Pastikan kembali goodbyedpi sudah disetting dengan benar
