### ISSUE TITLE
[BUG] rule34.paheal.net and xvideos.com

### ISSUE THREAD

**Issue by palmsugar26** [gvoze32/bebasid#814]
IP buat rule34.paheal.net gak berfungsi, nyari sendiri nemu IP yg work = 5.79.66.75

tambahan sub-domain for xvideos

8.252.38.123 static-l3.xvideos.com
8.252.37.123 static-l3.xvideos.com
67.26.251.251 static-l3.xvideos.com
152.195.13.91 static-egc.xvideos-cdn.com
141.0.168.12 static-ss.xvideos-cdn.com
141.0.168.13 static-ss.xvideos-cdn.com
141.0.168.14 static-ss.xvideos-cdn.com
141.0.168.15 static-ss.xvideos-cdn.com
8.252.10.251 hls4-l3.xvideos-cdn.com
8.252.33.123 hls4-l3.xvideos-cdn.com
8.253.185.93 hls4-l3.xvideos-cdn.com
152.195.13.88 vid-egc.xvideos-cdn.com
152.195.13.91 cdn77-pic.xvideos-cdn.com
185.246.209.24 cdn77-pic.xvideos-cdn.com
152.195.13.91 img-egc.xvideos-cdn.com
152.195.13.91 img-hw.xvideos-cdn.com
8.253.251.123 img-l3.xvideos-cdn.com
8.253.245.251 img-l3.xvideos-cdn.com
8.253.246.123 img-l3.xvideos-cdn.com
178.79.244.53 porn1-im-7688ec00-10333156-hlsinths.x.xvideos.com

**Comment by gvoze32** [comment]
Mantap gan zeeeb
