### ISSUE TITLE
[BUG] example.com

### ISSUE THREAD

**Issue by AhmadShiddiq** [gvoze32/bebasid#818]
**Deskripsi mengenai bug**
Setelah menyuntikkan hosts, saya coba untuk buka web2 yang ada di daftar. ada beberapa website yang bisa di buka seperti reddit, pirate bay.
Tapi ada juga banyak website yang tidak bisa keluar dan diblokir seperti di ss.

**Screenshot**
![image](https://user-images.githubusercontent.com/53107961/70059978-4a4def80-1614-11ea-980d-97fc7e10cfbd.png)

**Device**
 - OS: [Manjaro]
 - Browser [cth. Chrome]

**Comment by gvoze32** [comment]
Untuk instalasi linux coba pakai cara yang alternatif, dan setelah pasang coba restart pc kembali.

**Comment by AhmadShiddiq** [comment]
Alternatif yang mana pak?
apa yang pake openvpn itu ya?

**Comment by gvoze32** [comment]
https://github.com/gvoze32/bebasid/blob/master/dev/readme/USAGE.md#linux

Paling bawah yang pakai wget

**Comment by AhmadShiddiq** [comment]
udah di tes pak, dah hasilnya masih sama.
sebenernya di android gitu juga sama kasus nya.

**Comment by gvoze32** [comment]
Ada problem sama device atau routernya mungkin pak

**Comment by AhmadShiddiq** [comment]
Saya baru tes pake 2 jaringan sih, pertama indihome dirumah. Kedua pake wifi.id di warkop.
