### ISSUE TITLE
[BUG] netflix super slow connection

### ISSUE THREAD

**Issue by tamastro** [gvoze32/bebasid#828]
**Deskripsi mengenai bug**
netflix bisa di buka tapi lemot banget, padahal fast.com bisa di buka dan speednya cepat

**Screenshot**
<img width="1792" alt="Screen Shot 2019-12-10 at 02 47 34" src="https://user-images.githubusercontent.com/28701137/70467287-7deab700-1af7-11ea-8489-8aeb88994dad.png">
<img width="1792" alt="Screen Shot 2019-12-10 at 02 48 17" src="https://user-images.githubusercontent.com/28701137/70467313-8b07a600-1af7-11ea-9ee8-2a7f50acce47.png">

**Device**
 - OS: mac os catalina 10.15.1
 - Browser chrome
- dnscrypt & green tunnel installed

**Comment by gvoze32** [comment]
Deactivate dnscrypt kemudian update hosts
