### ISSUE TITLE
[BUG] netflix.com

### ISSUE THREAD

**Issue by vindytr** [gvoze32/bebasid#854]
Netflix pake indihome udah gabisa lagi, jadi dari login sampe homepage dan ngesearch film2nya cepat tapi pas udah mainin filmnya cuman muter terus bro. udah coba reinstall goodbye dpi dan bebas id hasilnya sama thanks

![Picture1](https://user-images.githubusercontent.com/46719733/72253858-1e6f5200-3635-11ea-827f-6accecf97f21.png)

**Device**
 - OS: [cth. Windows 7]
 - Browser [cth. Chrome, Firefox]

**Comment by tova04** [comment]
Same, gw juga, setelah muter-muter lama, ujungnya Error Code: M7037-1105

![image](https://user-images.githubusercontent.com/56639578/72260113-ac9f0480-3644-11ea-8722-84f98fe2bc02.png)

OS: Windows 10
Browser: Chrome

**Comment by danufirmansyah** [comment]
sama nih gw juga, uda gabisa pas sore tadi

**Comment by mashilman** [comment]
Sama nih, baru berasa kemaren sore ga bisa akses, malemnya coba lagi sempet bisa nonton satu episode, habis itu ga bisa lagi sampai pagi ini

**Comment by boyriot** [comment]
wah udah ga bisa  ya :(

**Comment by gvoze32** [comment]
Untuk info progress bisa pantengin channel discord bebasid

**Comment by boyriot** [comment]
ga ada bro gw cari channel bebasid

**Comment by g4r15** [comment]
lah itu di halaman utama https://github.com/gvoze32/bebasid enggak liat ada kotak abu2 tulisan 'discord' dan kotak ijo di sampingnya yang ada tulisan 'xx online' ??

**Comment by boyriot** [comment]
oh iya, sori, thx bro.

**Comment by gvoze32** [comment]
Untuk sementara bisa pakai metode VPN Alternatif
https://github.com/gvoze32/bebasid/blob/master/dev/readme/NETFLIX.md#vpn-alternatif
