### ISSUE TITLE
[BUG] Link untuk mendownload BEBASID not found/broken

### ISSUE THREAD

**Issue by StevenAmadeus** [gvoze32/bebasid#857]
**Deskripsi mengenai bug**
Deskripsi yang jelas dan ringkas tentang apa yang terjadi.

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 7]
 - Browser [cth. Chrome, Firefox]

**Comment by gvoze32** [comment]
https://github.com/gvoze32/bebasid/blob/master/dev/readme/USAGE.md#windows
