### ISSUE TITLE
[BUG] Tidak bisa download bebasid 404

### ISSUE THREAD

**Issue by shandytp** [gvoze32/bebasid#858]
**Deskripsi mengenai bug**
Tidak bisa download bebasid.exe

**Screenshot**
Jika ada, tambahkan ss untuk membantu menjelaskan mengenai bug.

**Device**
 - OS: [cth. Windows 7]
 - Browser [cth. Chrome, Firefox]

**Comment by gvoze32** [comment]
https://github.com/gvoze32/bebasid/blob/master/dev/readme/USAGE.md#windows
